FROM node:alpine

WORKDIR /app

ENV TOKEN=MTA0OTUxNDU2NzUyMjMzMjc4NA.GevTy5.pyx8iL8oiIFKmr52UcPBMTDV_d8qvzVkLO_puo

ENV GOOGLE_KEY=AIzaSyBdcjfVg7ntI3yuE0Xx6I0KCzkbH9F8kdA

COPY . .


RUN ["npm", "install"]

CMD ["npm", "start"]